### ISSUE TITLE
Generate conda release for ease of install and updating

### ISSUE THREAD

**Issue by durack1** [PCMDI/nominal_resolution#6]
I tried to install this package a week ago and hit issues, if it was wrapped up in a conda package this would be ideal, which would facilitate use, and in particular updating if we hit issues with certain grids.

A use case would be (after installing)
```python
>>> import nominal_resolution
>>> import cdms2 as cdm
>>> f = 'infile.nc'
>>> fH = cdm.open(f)
>>> data = fH['variable']
...
>>> nomRes = nominal_resolution.mean_resolution(cellarea, latitude_bounds, longitude_bounds,
convertdeg2rad, returnMaxDistance=False)
```

**Comment by durack1** [comment]
@doutriaux1 great, should this appear at https://anaconda.org/PCMDI/ or somewhere else?

**Comment by doutriaux1** [comment]
https://anaconda.org/PCMDI/nominal_resolution
